i created layout for 1440px
Junedsgn/hardware pull request #1
Opened 2022-12-15 17:30 UTC by Junedsgn

2022-12-15 17:33 UTC, Artem29383 requested changes

2022-12-15 17:33 UTC, Artem29383 commented on styles/normalize.min.css
> +@charset "UTF-8";
Тест

2022-12-15 17:33 UTC, Junedsgn commented on styles/normalize.min.css
> +@charset "UTF-8";
поменяли ок

2022-12-15 17:37 UTC, Artem29383 requested changes

2022-12-15 17:37 UTC, Artem29383 commented on styles/normalize.min.css
> +*, *::before, *::after {
good

2022-12-17 11:22 UTC, Artem29383 requested changes

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    padding-bottom: 35px;
надо добавить боковые паддинги, как на макете и убрать margin-left у элементов 
hardware__text и hardware_svg

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    align-items: center;
Надо добавить паддинги     padding: 0 12px 0 40px;
как на макете и убрать лишние марджины у элементов 
header__burger и header__search

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    top: 9px;
лишнее, или если с помощью этого сходиться с pixel perfect, то заменить на margin-top

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-family: PT_SANS_CAPTION;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-style: normal;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-style: normal;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-weight: 400;
лишнеелишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    position: relative;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    bottom: 7px;
margin-top: -7px

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-style: normal;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    color: white;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    text-align: right;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    color: white;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +.margin-45 {
Сделай отдельный файл со спец классами и вынеси их все туда

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    color: white;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-style: normal;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    max-width: 720px;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    color: white;
лишнее

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    font-style: normal;
лишнее
Пробегись по всем классам и удали везде лишние стили которые уже по стандарту применены к элементам

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +.row {
Тоже в отдельный файл

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    margin-bottom: 25px;
оберни все элементы с main__content__container в общий див и задай gap 25 margin-bottom удали у main__content__container и задай его новому общему диву который будет оборачивать все карточки

У тебя из-за него сейчас почему то в medium_content margin-bottom 28 а в small_content 25 хотя они в одной строке 

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/54779368/208232294-ab99e531-48dc-4119-bae3-a06cede47481.png">

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/54779368/208232304-e320e495-b165-43ba-b11f-ab1572ee24c6.png">

2022-12-17 11:22 UTC, Artem29383 commented on index.html
> +                <div>
лишний див

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    width: 380px;
лишнее, у тебя уже задано     grid-template-columns: 1fr 1fr выше

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +.article-title {
вместо этого .main__content-pic .article-title {
  flex-grow: 1
}

Сейчас у тебя класс article-title используется и в других местах, но там оно не работает и неактивно, если что-то поменяется то случайным образом сломает тебе верстку

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> + .content__right-section {
лишний класс, удали и свойства эти и класс (тут и в html)

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    margin-top: 25px
убрать и заменить на это и посмотреть что будет, так же убрать ПОЛНОСТЬЮ margin у content_element
display: flex;
    flex-direction: column;
    gap: 22px;
    padding-top: 10px;
    margin-top: 15px;

2022-12-17 11:22 UTC, Artem29383 commented on styles/style.css
> +    margin-top: 25px
это решит проблему с тем что у тебя плохо видна черточка острая от точки

2022-12-17 19:51 UTC, Artem29383 commented on styles/style.css
> +    font-family: PT_SANS_CAPTION;
font-style: normal;
    font-weight: 400;

2022-12-18 14:49 UTC, Junedsgn commented on styles/style.css
> +    align-items: center;
сделала

2022-12-18 14:59 UTC, Junedsgn commented on styles/style.css
> +    color: white;
done

2022-12-18 15:00 UTC, Junedsgn commented on styles/style.css
> +    color: white;
done

2022-12-18 15:00 UTC, Junedsgn commented on styles/style.css
> +    font-style: normal;
done

2022-12-18 15:01 UTC, Junedsgn commented on styles/style.css
> +    max-width: 720px;
done

2022-12-18 15:01 UTC, Junedsgn commented on styles/style.css
> +    color: white;
done

2022-12-18 15:01 UTC, Junedsgn commented on styles/style.css
> +    font-style: normal;
done

2022-12-18 15:13 UTC, Junedsgn commented on styles/style.css
> +    margin-bottom: 25px;
обернула в новый див  main__containers
в итоге отступ от блоков отсутствует 
почему?

2022-12-18 15:14 UTC, Junedsgn commented on index.html
> +                <div>
готово

2022-12-18 15:16 UTC, Junedsgn commented on styles/style.css
> +.article-title {
не поняла

2022-12-18 15:22 UTC, Junedsgn commented on styles/style.css
> + .content__right-section {
done

2022-12-18 17:30 UTC, Junedsgn commented on styles/style.css
> +    margin-bottom: 25px;
done

2022-12-18 17:37 UTC, Junedsgn commented on styles/style.css
> +.margin-45 {
done

2022-12-18 17:46 UTC, Junedsgn commented on styles/style.css
> +.article-title {
done

2022-12-18 17:46 UTC, Junedsgn commented on styles/style.css
> +.row {
done

2022-12-18 17:47 UTC, Junedsgn commented on styles/style.css
> +    color: white;
done

2022-12-18 17:47 UTC, Junedsgn commented on styles/style.css
> +    font-style: normal;
done

2022-12-18 17:47 UTC, Junedsgn commented on styles/style.css
> +    font-style: normal;
done

2022-12-18 17:47 UTC, Junedsgn commented on styles/style.css
> +    font-style: normal;
done

2022-12-18 17:47 UTC, Junedsgn commented on styles/style.css
> +    font-family: PT_SANS_CAPTION;
done

2022-12-18 17:54 UTC, Junedsgn commented on styles/style.css
> +    align-items: center;
теперь точно сделано

2022-12-18 18:01 UTC, Junedsgn commented on styles/style.css
> +    padding-bottom: 35px;
done

2022-12-18 18:09 UTC, Junedsgn commented on styles/style.css
> +    top: 9px;
done

2022-12-18 18:10 UTC, Junedsgn commented on styles/style.css
> +    font-weight: 400;
done

2022-12-18 18:10 UTC, Junedsgn commented on styles/style.css
> +    position: relative;
done

2022-12-18 18:11 UTC, Junedsgn commented on styles/style.css
> +    text-align: right;
done

2022-12-18 18:12 UTC, Junedsgn commented on styles/style.css
> +    width: 380px;
done

2022-12-18 18:23 UTC, Junedsgn commented on styles/style.css
> +    margin-top: 25px
done

2022-12-18 18:23 UTC, merged